spring:
  application:
    name: cinemaster-be
  flyway:
    url: jdbc:h2:mem:cinemaster
    user: sa
    password: sa
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cinemaster
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  servlet:
    context-path: /api
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
h2:
  tcp:
    enabled: true
    port: 8082
  web:
    enabled: true
    port: 8083